-- MySQL Script generated by MySQL Workbench
-- Thu Apr 23 20:48:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema menutti
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema menutti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `menutti` DEFAULT CHARACTER SET utf8 ;
USE `menutti` ;

-- -----------------------------------------------------
-- Table `menutti`.`categoria_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menutti`.`categoria_produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `menutti`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menutti`.`mesa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `menutti`.`cargo_funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menutti`.`cargo_funcionarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_cargo` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `menutti`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menutti`.`funcionarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(250) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `senha` VARCHAR(250) NOT NULL,
  `id_cargo` INT NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`id`),
  INDEX `cargo_func_idx` (`id_cargo` ASC),
  CONSTRAINT `cargo_func`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `menutti`.`cargo_funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `menutti`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menutti`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `foto` VARCHAR(300) NOT NULL,
  `nome_produto` VARCHAR(250) NOT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  `preco` DECIMAL NOT NULL,
  `id_categoria` INT NOT NULL,
  `id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_produto_UNIQUE` (`nome_produto` ASC),
  INDEX `categoria_produto_idx` (`id_categoria` ASC),
  INDEX `func_cadastrar_idx` (`id_funcionario` ASC),
  CONSTRAINT `categoria_produto`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `menutti`.`categoria_produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `func_cadastrar`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `menutti`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `menutti`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menutti`.`ingredientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_ingt` VARCHAR(250) NOT NULL,
  `adicional` TINYINT NOT NULL,
  `id_adicional` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `menutti`.`contem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menutti`.`contem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `id_ingredientes` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `produto_idx` (`id_produto` ASC),
  INDEX `ingrediente_produto_idx` (`id_ingredientes` ASC),
  CONSTRAINT `produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `menutti`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ingrediente_produto`
    FOREIGN KEY (`id_ingredientes`)
    REFERENCES `menutti`.`ingredientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `menutti`.`adc_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menutti`.`adc_produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `id_ingrediente` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `produto_add_idx` (`id_produto` ASC),
  INDEX `ingrediente_add_idx` (`id_ingrediente` ASC),
  CONSTRAINT `produto_add`
    FOREIGN KEY (`id_produto`)
    REFERENCES `menutti`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ingrediente_add`
    FOREIGN KEY (`id_ingrediente`)
    REFERENCES `menutti`.`ingredientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `menutti`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menutti`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_mesa` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `finalizado` INT NOT NULL,
  `observacao` VARCHAR(250) NULL,
  `data` DATETIME NOT NULL,
  `id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `func_adc_idx` (`id_funcionario` ASC),
  CONSTRAINT `pedido_mesa`
    FOREIGN KEY (`id_mesa`)
    REFERENCES `menutti`.`mesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `produto_pedido`
    FOREIGN KEY (`id_produto`)
    REFERENCES `menutti`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `func_adc`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `menutti`.`funcionarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `menutti`.`pedido_adc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menutti`.`pedido_adc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pedido` INT NOT NULL,
  `id_adicional` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `adicional_produto_idx` (`id_adicional` ASC),
  INDEX `adc_pedido_idx` (`id_pedido` ASC),
  CONSTRAINT `adicional_produto`
    FOREIGN KEY (`id_adicional`)
    REFERENCES `menutti`.`ingredientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `adc_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `menutti`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
